syntax on
set tabstop=2
set softtabstop=2
set number
set showcmd
filetype indent on
set wildmenu
set showmatch
set foldenable
set foldmethod=indent

call vundle#begin()
Plugin 'preservim/nerdtree'
Plugin 'valloric/youcompleteme'
Plugin 'scrooloose/syntastic'
call vundle#end()

filetype plugin indent on
