[colors.primary]
background = "#202222"
foreground = "#c3c3c3"

[colors.cursor]
text = "#0f1212"
cursor = "#c3c3c3"

[colors.vi_mode_cursor]
text = "#0f1212"
cursor = "#c3c3c3"

[colors.search.matches]
foreground = "#0f1212"
background = "#c3c3c3"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#596d6d"
background = "#c3c3c3"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0f1212"
red = "#455B4C"
green = "#526852"
yellow = "#546E6C"
blue = "#607767"
magenta = "#718871"
cyan = "#788E7D"
white = "#c3c3c3"

[colors.bright]
black = "#596d6d"
red = "#455B4C"
green = "#526852"
yellow = "#546E6C"
blue = "#607767"
magenta = "#718871"
cyan = "#788E7D"
white = "#c3c3c3"

[colors.dim]
black = "#c3c3c3"
red = "#455B4C"
green = "#718871"
yellow = "#546E6C"
blue = "#607767"
magenta = "#526852"
cyan = "#788E7D"
white = "#596d6d"
